package com.cognizant.jwtauth.controller;

import com.cognizant.jwtauth.dto.AuthRequest;
import com.cognizant.jwtauth.dto.AuthResponse;
import com.cognizant.jwtauth.security.JwtTokenProvider;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * AuthController – Exercise 3
 *
 * Handles authentication requests and issues JWT tokens.
 *
 * POST /auth/login
 *   Request body:  { "username": "user", "password": "password" }
 *   Response body: { "token": "eyJ..." }
 *
 * The {@link AuthenticationManager} delegates to the configured
 * {@link org.springframework.security.core.userdetails.UserDetailsService}
 * to verify credentials. On success, a JWT is generated by
 * {@link JwtTokenProvider} and returned to the caller.
 */
@RestController
@RequestMapping("/auth")
public class AuthController {

    private final AuthenticationManager authenticationManager;
    private final JwtTokenProvider      jwtTokenProvider;

    public AuthController(AuthenticationManager authenticationManager,
                          JwtTokenProvider      jwtTokenProvider) {
        this.authenticationManager = authenticationManager;
        this.jwtTokenProvider      = jwtTokenProvider;
    }

    /**
     * Authenticates the user and returns a signed JWT on success.
     *
     * @param request DTO containing username and password
     * @return 200 OK with {@link AuthResponse} containing the JWT
     * @throws org.springframework.security.core.AuthenticationException
     *         if credentials are invalid (returns HTTP 401 automatically)
     */
    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@RequestBody AuthRequest request) {
        // 1. Authenticate using the configured UserDetailsService + PasswordEncoder
        Authentication auth = authenticationManager.authenticate(
            new UsernamePasswordAuthenticationToken(
                request.username(), request.password()
            )
        );

        // 2. Extract roles from the authenticated principal
        List<String> roles = auth.getAuthorities()
                                 .stream()
                                 .map(GrantedAuthority::getAuthority)
                                 // Strip the "ROLE_" prefix added by Spring Security
                                 .map(role -> role.replace("ROLE_", ""))
                                 .toList();

        // 3. Create and return the JWT
        String token = jwtTokenProvider.createToken(auth.getName(), roles);
        return ResponseEntity.ok(new AuthResponse(token));
    }
}
